services:
  namenode:
    image: bardend123/hadoop-namenode:v1
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name

    environment:
      - CLUSTER_NAME=test
      - NAMENODE_HOST=namenode
      - REPLICATION_FACTOR=4

    networks:
      - hadoop-network
  
  datanode:
    image: bardend123/hadoop-datanode:v1
    container_name: datanode
    volumes:
      - datanode:/hadoop/dfs/data
  
    environment:
      - NAMENODE_HOST=namenode
      - REPLICATION_FACTOR=4
    
    networks:
      - hadoop-network
    depends_on:
      - namenode
  
  nodemanager:
    image: bardend123/hadoop-nodemanager:v1
    container_name: nodemanager
    networks:
      - hadoop-network
    
  resourcemanager:
    image: bardend123/hadoop-resourcemanager:v1
    container_name: resourcemanager
    networks:
      - hadoop-network

networks:
  hadoop-network:

volumes:
  namenode:
  datanode: