version: '3.8'
services:
  namenode:
    image: bardend123/hadoop-namenode:v1
    volumes:
      - namenode:/hadoop/dfs/name
    
    environment:
      - CLUSTER_NAME=test
    networks:
      - start-dfs
  
  datanode:
    image: bardend123/hadoop-datanode:v1
  
    volumes:
      - datanode:/hadoop/dfs/data
  
    environment:
      - SERVICE_PRECONDITION="namenode:50070"
    
    networks:
      - start-dfs
    depends_on:
      - namenode

networks:
  start-dfs:

volumes:
  namenode:
  datanode: