services:
  namenode:
    image: bardend123/hadoop-namenode:v1
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name

    environment:
      - CLUSTER_NAME=test
      - NAMENODE_HOST=namenode
      - REPLICATION_FACTOR=4

    networks:
      - start-dfs
  
  datanode:
    image: bardend123/hadoop-datanode:v1
    container_name: datanode
    volumes:
      - datanode:/hadoop/dfs/data
  
    environment:
      - NAMENODE_HOST=namenode
      - REPLICATION_FACTOR=4
    
    networks:
      - start-dfs
    depends_on:
      - namenode

networks:
  start-dfs:

volumes:
  namenode:
  datanode: