services:
  namenode:
    image: bardend123/hadoop-namenode:v2
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name

    environment:
      - CLUSTER_NAME=test
      - NAMENODE_HOST=namenode
      - REPLICATION_FACTOR=4

    networks:
      - hadoop-network
  
  datanode:
    image: bardend123/hadoop-datanode:v2
    container_name: datanode
    volumes:
      - datanode:/hadoop/dfs/data
  
    environment:
      - NAMENODE_HOST=namenode
      - REPLICATION_FACTOR=4
    
    networks:
      - hadoop-network
    depends_on:
      - namenode
  spark-master:
    image: bardend123/spark-master:v2
    container_name: spark-master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - hadoop-network
 
networks:
  hadoop-network:

volumes:
  namenode:
  datanode: